name: Discord Webhook

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: send events to Discord
        run: |
          COMMITS=$(jq -r '.commits[] | "- [" + .message + "](" + .url + ")"' "$GITHUB_EVENT_PATH")

          curl -H "Content-Type: application/json" \
          -d "{
            \"embeds\": [{
              \"title\": \"New Push to ${{ github.repository }}\",
              \"color\": 5814783,
              \"author\": {
                \"name\": \"${{ github.actor }}\",
                \"icon_url\": \"https://github.com/${{ github.actor }}.png\"
              },
              \"description\": \"$COMMITS\",
              \"footer\": {
                \"text\": \"GitHub Actions\"
              },
              \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"
            }]
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}